# Generated by Django 2.2.4 on 2021-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_ya_beat_app', '0001_initial'),
        ('login_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='beats_liked',
            field=models.ManyToManyField(related_name='users', through='sell_ya_beat_app.Like', to='sell_ya_beat_app.Beat'),
        ),
    ]
